// ------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン: 17.0.0.0
//  
//     このファイルへの変更は、正しくない動作の原因になる可能性があり、
//     コードが再生成されると失われます。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Enumeration.Generator
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using Microsoft.CodeAnalysis;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    internal partial class EnumerationStructTemplate : EnumerationStructTemplateBase
    {
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
 if(this.Options.IsNamespaceSpecified) { 
            this.Write("namespace ");
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Options.Namespace));
            this.Write("\r\n{\r\n");
 } 
            this.Write("\treadonly partial struct ");
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Options.Name));
            this.Write(" \r\n\t{\r\n\t\tpublic enum Case \r\n\t\t{\r\n\t\t\t");
            this.Write(this.ToStringHelper.ToStringWithCulture(string.Join(", ", this.Options.Methods.Select(method => method.Name))));
            this.Write("\r\n\t\t}\r\n\t\tstruct __Implement\r\n\t\t{\r\n\t\t\t[global::System.Runtime.InteropServices.Stru" +
                    "ctLayout(System.Runtime.InteropServices.LayoutKind.Explicit)]\r\n\t\t\tpublic struct " +
                    "Unmanaged \r\n\t\t\t{\r\n");
 foreach(var method in this.Options.Methods) { 
            this.Write("\t\t\t\tpublic struct __");
            this.Write(this.ToStringHelper.ToStringWithCulture(method.Name));
            this.Write("\r\n\t\t\t\t{\r\n");
 foreach(var parameter in method.Parameters.Where(p => (p.Type is INamedTypeSymbol t) && !t.IsGenericType && t.IsUnmanagedType)) { 
            this.Write("\t\t\t\t\tpublic ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Helper.FullNameOf(parameter.Type)));
            this.Write(" ");
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Name));
            this.Write(";\r\n");
 } 
            this.Write("\t\t\t\t}\r\n");
 } 
            this.Write("\r\n");
 foreach(var method in this.Options.Methods) { 
            this.Write("\t\t\t\t[global::System.Runtime.InteropServices.FieldOffset(0)]\r\n\t\t\t\tpublic __");
            this.Write(this.ToStringHelper.ToStringWithCulture(method.Name));
            this.Write(" ");
            this.Write(this.ToStringHelper.ToStringWithCulture(method.Name));
            this.Write(";\r\n");
 } 
            this.Write("\t\t\t}\r\n\r\n\t\t\tpublic struct Managed\r\n\t\t\t{\r\n");
 for(var i = 0; i < this.Options.ReferenceTypeCount; ++i) { 
            this.Write("\t\t\t\tpublic global::System.Object __reference_");
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            this.Write(";\r\n");
 } 
 foreach(var (type, count) in this.Options.OtherTypes) { 
 for(var i = 0; i < count; ++i) { 
            this.Write("\t\t\t\tpublic ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Helper.FullNameOf(type)));
            this.Write(" ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Helper.EscapedFullNameOf(type)));
            this.Write("_");
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            this.Write(";\r\n");
 } 
 } 
            this.Write("\t\t\t}\r\n\r\n\t\t\tpublic Case type;\r\n\t\t\tpublic Unmanaged unmanaged;\r\n\t\t\tpublic Managed m" +
                    "anaged;\r\n\r\n\t\t\tpublic ");
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Options.Identifier));
            this.Write(" As() => global::System.Runtime.CompilerServices.Unsafe.As<__Implement, ");
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Options.Identifier));
            this.Write(">(ref this);\r\n\t\t}\r\n\r\n");
 foreach(var method in this.Options.Methods) { 
            this.Write("\t\tpublic static partial ");
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Options.Identifier));
            this.Write(" ");
            this.Write(this.ToStringHelper.ToStringWithCulture(method.Name));
            this.Write("(");
            this.Write(this.ToStringHelper.ToStringWithCulture(Helper.ParamsOf(method)));
            this.Write(") \r\n\t\t{\r\n\t\t\tvar impl = default(__Implement);\r\n\t\t\timpl.type = Case.");
            this.Write(this.ToStringHelper.ToStringWithCulture(method.Name));
            this.Write(";\r\n");
 foreach(var parameter in method.Parameters) { 
 if(parameter.Type.IsReferenceType) { 
 var index = method.Parameters.Count(p => p.Ordinal < parameter.Ordinal && p.Type.IsReferenceType); 
            this.Write("\t\t\timpl.managed.__reference_");
            this.Write(this.ToStringHelper.ToStringWithCulture(index));
            this.Write(" = ");
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Name));
            this.Write(";\r\n");
 } else if(parameter.Type is not INamedTypeSymbol || !parameter.Type.IsUnmanagedType) { 
 var index = method.Parameters.Count(p => p.Ordinal < parameter.Ordinal && Helper.SymbolEquals(p.Type, parameter.Type)); 
            this.Write("\t\t\timpl.managed.");
            this.Write(this.ToStringHelper.ToStringWithCulture(Helper.EscapedFullNameOf(parameter.Type)));
            this.Write("_");
            this.Write(this.ToStringHelper.ToStringWithCulture(index));
            this.Write(" = ");
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Name));
            this.Write(";\r\n");
 } else { 
            this.Write("\t\t\timpl.unmanaged.");
            this.Write(this.ToStringHelper.ToStringWithCulture(method.Name));
            this.Write(".");
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Name));
            this.Write(" = ");
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Name));
            this.Write(";\r\n");
 } 
 } 
            this.Write("\t\t\treturn impl.As();\r\n\t\t}\r\n\r\n\t\t[global::System.ComponentModel.EditorBrowsable(glo" +
                    "bal::System.ComponentModel.EditorBrowsableState.Never)]\r\n\t\tpublic static bool ");
            this.Write(this.ToStringHelper.ToStringWithCulture(method.Name));
            this.Write("(");
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Options.DeconstructMethodParamsOf(method)));
            this.Write(") \r\n\t\t{\r\n\t\t\tif (__self.Type == Case.");
            this.Write(this.ToStringHelper.ToStringWithCulture(method.Name));
            this.Write(")\r\n\t\t\t{\r\n");
 foreach(var parameter in method.Parameters) { 
 if(parameter.Type.IsReferenceType) { 
 var index = method.Parameters.Count(p => p.Ordinal < parameter.Ordinal && p.Type.IsReferenceType); 
            this.Write("\t\t\t\t");
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Name));
            this.Write(" = (");
            this.Write(this.ToStringHelper.ToStringWithCulture(Helper.FullNameOf(parameter.Type)));
            this.Write(")__self.__implement.managed.__reference_");
            this.Write(this.ToStringHelper.ToStringWithCulture(index));
            this.Write(";\r\n");
 } else if(parameter.Type is not INamedTypeSymbol || !parameter.Type.IsUnmanagedType) { 
 var index = method.Parameters.Count(p => p.Ordinal < parameter.Ordinal && Helper.SymbolEquals(p.Type, parameter.Type)); 
            this.Write("\t\t\t\t");
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Name));
            this.Write(" = __self.__implement.managed.");
            this.Write(this.ToStringHelper.ToStringWithCulture(Helper.EscapedFullNameOf(parameter.Type)));
            this.Write("_");
            this.Write(this.ToStringHelper.ToStringWithCulture(index));
            this.Write(";\r\n");
 } else { 
            this.Write("\t\t\t\t");
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Name));
            this.Write(" = __self.__implement.unmanaged.");
            this.Write(this.ToStringHelper.ToStringWithCulture(method.Name));
            this.Write(".");
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Name));
            this.Write(";\r\n");
 } 
 } 
            this.Write("\t\t\t\treturn true;\r\n\t\t\t}\r\n\r\n");
 foreach(var parameter in method.Parameters) { 
            this.Write("\t\t\t");
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Name));
            this.Write(" = default;\r\n");
 } 
            this.Write("\t\t\treturn false;\r\n\t\t}\r\n");
 } 
            this.Write("\r\n\t\treadonly __Implement __implement;\r\n\t\tpublic Case Type => this.__implement.typ" +
                    "e;\r\n\t}\r\n");
 if(this.Options.IsNamespaceSpecified) { 
            this.Write("}\r\n");
 } 
            return this.GenerationEnvironment.ToString();
        }
    }
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    internal class EnumerationStructTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
